### PR TITLE
Use `chttpd:qs` instead of `couch_httpd:qs`

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by kxepal** [comment]
+1

**Comment by rnewson** [comment]
this repo isn't listed in rebar.config at all...

**Comment by kxepal** [comment]
Hm...true. Wasn't it replaced by couchdb-global-changes ?

**Comment by rnewson** [comment]
yeah

**Comment by rnewson** [comment]
+1, might as well get this in even if we delete the repo later

**Pull request merged**
